default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: animategif1
  database: animategif1_development

test:
  <<: *default
  database: animategif1_test

production:
  <<: *default
  database: animategif1_production
  url: <%= ENV['DATABASE_URL'] %>
